name: Buildx using Github action templates
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        # why tho
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          target: php-dev
          push: true
          tags: ghcr.io/wojciechem/phperfect-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max