name: Buildx
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: pull latest image
        run: docker pull ghcr.io/wojciechem/phperfect-dev:latest
      -
        name: build images
        run: docker buildx bake
      -
        name: push
        run: docker image ls
#            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#            docker push ghcr.io/wojciechem/phperfect-dev --all-tags
