name: Buildx
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: build images
        run: docker buildx bake
      -
        name: push
        run: |
#        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker image ls
#        docker push ghcr.io/wojciechem/phperfect-dev --all-tags
