name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - ci
        uses: docker/build-push-action@v2
        with:
          context: .
          target: php-ci
          push: true
          tags: ghcr.io/wojciechem/phperfect:ci-latest
          # using github-specific, experimental feature...
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Tests
        run: docker run ghcr.io/wojciechem/phperfect:ci-latest vendor/bin/phpunit .
      -
        name: Build and push - prod
        uses: docker/build-push-action@v2
        with:
          context: .
          target: php-prod
          push: true
          tags: ghcr.io/wojciechem/phperfect:latest
          # using github-specific, experimental feature...
          cache-from: type=gha
          cache-to: type=gha,mode=max
